### ISSUE TITLE
Swift 3/4 Support

### ISSUE THREAD

**Issue by alexsteinerde** [pixyzehn/SnowFalling#3]
Please add Swift 3/4 support for this project.

**Comment by omarzl** [comment]
I made a fork and update it to Swift 4:
https://github.com/omarzl/SnowFalling
I will not maintain the project, I did it because I need it too, feel free to use it if you still require it

**Comment by alexsteinerde** [comment]
Thanks for the link. I used the following fork: https://github.com/bleedsy/SnowFalling but yours is more update to date with the original I think.
